# Generated by Django 5.0.4 on 2024-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "mob_no",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("user_company_name", models.CharField(max_length=20)),
                ("user_company_address", models.CharField(max_length=30)),
                ("user_company_pincode", models.BigIntegerField()),
            ],
        ),
    ]
