# Generated by Django 5.0.4 on 2024-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="user_company_address",
            field=models.TextField(max_length=30),
        ),
    ]
