# Generated by Django 5.0.4 on 2024-05-20 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billApp", "0006_alter_userdetails_user_company_name_billdetails_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvoiceProductDetails",
        ),
    ]
