# Generated by Django 5.0.4 on 2024-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billApp", "0008_invoiceproductdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceproductdetails",
            name="bill_number",
            field=models.CharField(max_length=6),
        ),
    ]
